on:
  push:
   branches:
    - master

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build
    steps:
     - name: nodejs
       uses: actions/setup-node@v2
       with:
        node-version: 14
     - run: npm install
     - run: npm build
      with:
        name: public-art
        path: public/
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          name: public-art
          path: public/
          username: ${{ secrets.USER }}
          server: ${{ secrets.SERVER }}
          ssh_private_key: ${{ secrets.KEY }} 
          local_path: './public/*'
          remote_path: '/var/www/other/joiceapp/www/public'
          args: '-o ConnectTimeout=5'
