on:
  push:
   branches:
    - master

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build
    steps:
     - name: nodejs
       uses: actions/setup-node@v2
       with:
        node-version: 14
     - run: npm i
     - run: npm run build

     - name: Build publics
       uses: actions/upload-artifact@v2
       with:
         name: public-artifact
         path: public
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Assets to upload
        uses: actions/download-artifact@v2
        with:
         name: public-artifact
         path: public

      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.USER }}
          server: ${{ secrets.SERVER }}
          ssh_private_key: ${{ secrets.KEY }} 
          local_path: './public/*'
          remote_path: '/var/www/other/${{ secrets.USER }}/www/public'
          args: '-o ConnectTimeout=5'
